# Generated by Django 2.2.3 on 2023-05-17 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_create_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='createdAt',
        ),
    ]
