# Generated by Django 2.2.3 on 2023-05-17 08:51

from django.db import migrations, models
from datetime import date


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_remove_member_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='createdAt',
            field=models.DateField(default=date(1998,1,1), verbose_name='Created At'),
            preserve_default=False,
        ),
    ]
