# Generated by Django 2.2.3 on 2023-05-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='createdAt',
            field=models.DateField(auto_now_add=True, verbose_name='Created At'),
        ),
    ]
