# Generated by Django 2.2.3 on 2023-05-17 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20230517_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='createdAt',
        ),
    ]
