# Generated by Django 2.2.3 on 2023-05-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_remove_member_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='createdAt',
            field=models.DateTimeField(default='1999-11-11', verbose_name='Created At'),
        ),
    ]
