# Generated by Django 2.2.3 on 2023-05-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_member_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='createdAt',
            field=models.DateField(default='1999-11-11', verbose_name='Created At'),
        ),
    ]
