# Generated by Django 2.2.3 on 2023-05-18 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20230517_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='createdAt',
            field=models.DateField(auto_now_add=True, verbose_name='Created At'),
        ),
    ]
