# Generated by Django 4.2.1 on 2023-05-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InuObsMi',
            fields=[
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.BigIntegerField()),
                ('obs_time', models.DateTimeField()),
                ('pow', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('temp', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('mb', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('mb_std', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('delta', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('vi_time', models.DateTimeField(blank=True, null=True)),
                ('inu_depth', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'inu_obs_mi',
                'managed': True,
            },
        ),
    ]
