# Generated by Django 4.2.1 on 2023-05-23 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('test1', models.CharField(max_length=200)),
            ],
        ),
    ]
