# Generated by Django 4.2.1 on 2023-05-23 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dummy'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dummy',
            table='dummy',
        ),
    ]
