# Generated by Django 4.2.1 on 2023-05-23 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_apitest_authgroup_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='djangomigrations',
            options={'managed': True},
        ),
    ]
