# Generated by Django 4.2.1 on 2023-05-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_djangomigrations_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalObsvtInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obscd', models.IntegerField(blank=True, null=True)),
                ('addr', models.TextField(blank=True, null=True)),
                ('bbsncd', models.TextField(blank=True, null=True)),
                ('bedslp', models.IntegerField(blank=True, null=True)),
                ('bsnara', models.FloatField(blank=True, null=True)),
                ('gdt', models.FloatField(blank=True, null=True)),
                ('lat', models.TextField(blank=True, null=True)),
                ('lon', models.TextField(blank=True, null=True)),
                ('mggvcd', models.TextField(blank=True, null=True)),
                ('mxgrd', models.FloatField(blank=True, null=True)),
                ('obskdcd', models.TextField(blank=True, null=True)),
                ('obsnm', models.TextField(blank=True, null=True)),
                ('obsnmeng', models.TextField(blank=True, null=True)),
                ('obsopndt', models.TextField(blank=True, null=True)),
                ('olendobsdh', models.IntegerField(blank=True, null=True)),
                ('olstartobsdh', models.IntegerField(blank=True, null=True)),
                ('rivnm', models.TextField(blank=True, null=True)),
                ('rvmjctdis', models.FloatField(blank=True, null=True)),
                ('rvwdt', models.IntegerField(blank=True, null=True)),
                ('sbsncd', models.IntegerField(blank=True, null=True)),
                ('siendobsdh', models.IntegerField(blank=True, null=True)),
                ('sistartobsdh', models.IntegerField(blank=True, null=True)),
                ('tdeyn', models.TextField(blank=True, null=True)),
                ('tmx', models.IntegerField(blank=True, null=True)),
                ('tmy', models.IntegerField(blank=True, null=True)),
                ('wlobscd', models.IntegerField(blank=True, null=True)),
                ('wltel', models.FloatField(blank=True, null=True)),
                ('wsrdis', models.TextField(blank=True, null=True)),
                ('lat_md', models.FloatField(blank=True, null=True)),
                ('lon_md', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
